---
title: "EDLD 652 Final"
output: 
  flexdashboard::flex_dashboard:
    css: css_script.css
    orientation: columns
    vertical_layout: fill
    source_code: https://chhr1s.github.io/GA_DOE_Public/docs/index.html/
---

```{r setup}
library(flexdashboard)
library(reactable)
library(tidyverse)
library(rio)
library(here)
library(janitor)
library(sf)
library(leaidr)
#devtools::install_github('ivelasq/leaidr', force = T)
library(tigris)
library(gt)
library(glmertree)
library(plotly)
library(colorblindr)
library(ggparty)
library(gganimate)
library(mice)
options(tigris_use_cache = TRUE)
options(tigris_class = "sf")
```

```{r, echo = F}
frl <- import(here("Data", "Free Reduced Lunch (FRL) Fiscal Year2019 Data Report_Schools.csv")) %>% 
  clean_names() %>% 
  mutate(kk_12_percent_frl = as.numeric(kk_12_percent_frl) 
         #kk_12_percent_frl = replace_na(kk_12_percent_frl, 0)
         ) %>% 
  separate(col = school_id_school_name, 
           into = c('school_id','school_name'), 
           sep = " - ",
           extra = "merge") %>% 
  filter(system_name != 'N/A') %>% 
  select(-system_id)

all_students <-  #https://gosa.georgia.gov/report-card-dashboards-data/downloadable-data
  import(
    here('Data',
         'Enrollment_By_Grade_Level_2019_Dec2nd_2019.csv')) %>%
  clean_names() %>% 
  filter(enrollment_period == 'Fall') %>% 
  group_by(instn_name) %>% 
  summarize(num_students = sum(enrollment_count)) %>% 
  transmute(school_name = instn_name, 
            total = num_students)


school_demos <- import(
    here('Data', #https://gosa.georgia.gov/report-card-dashboards-data/downloadable-data
  'Enrollment_by_Subgroups_Programs_2019_OCT_22_2020.csv')) %>% 
  clean_names() %>% 
  transmute(school_name = instn_name,
            system_name = school_dstrct_nm,
            perc_black = enroll_percent_black,
            perc_hisp = enroll_percent_hispanic, 
            perc_white = enroll_percent_white, 
            perc_migrant = enroll_percent_migrant, 
            perc_esol = enroll_pct_esol
            )
  
schools <- school_demos %>%
  full_join(all_students)

disc_action <- import(
  here("Data", 
       "sr2019_discipline_action_counts_sch.xlsx")
  ) %>% 
  clean_names() %>% 
  select(-grade_range, -school_year) %>% 
  left_join(frl)

  ### There are a problem with districts where no schools reported FRL
  ### In these districts, the average of all = 0 (with na.rm = T), 
  ### Unsure how to handle these...


dat <- disc_action %>% 
  left_join(schools) %>% # if this is left_join I have to impute
  group_by(system_name) %>% 
  mutate(harsh =
           out_of_school_suspension_oss +
           juvenile_court_referral +
           physical_restraint +
           corporal_punishment +
           permanent_expulsion, # +
           #in_school_suspension_iss,
         district = factor(system_name),
         school_name = factor(school_name), 
         fac_schtype = factor(fac_schtype), 
         perc_frl = kk_12_percent_frl 
         ) %>% 
  select(district, 
         #district_size, 
         school_name, 
         fac_schtype, 
         total,
         contains('frl'),
         contains('black'), 
         contains('hisp'), 
         contains('white'), 
         contains('migrant'), 
         contains('esol'), 
         contains('harsh')) %>% 
  select(-kk_12_percent_frl)

imputed <- dat %>% 
  select(total:harsh) %>% 
  mice::mice(m = 1, seed = 12345, remove.collinear = T, print = F) %>% 
  mice::complete(1)

dat_imp <- dat %>%
  select(district, school_name, fac_schtype) %>%
  bind_cols(imputed)

dat_final <- dat_imp %>%
  mutate(harsh_ps = harsh/total, 
         harsh_per_100 = harsh_ps*100, 
         perc_non_white = 100-perc_white) %>% 
  group_by(district) %>% 
  mutate(district_size = sum(total, na.rm = T),
         d_black = sum(total*perc_black, na.rm = T)/district_size,
         d_hisp = sum(total*perc_hisp, na.rm = T)/district_size,
         d_non_white = sum(total*perc_non_white, na.rm = T)/district_size,
         d_white = sum(total*perc_white, na.rm = T)/district_size,
         d_esol = sum(total*perc_esol, na.rm = T)/district_size,
         d_migrant = sum(total*perc_migrant, na.rm = T)/district_size,
         d_frl = sum(total*perc_frl, na.rm = T)/district_size,
         d_harsh = sum(harsh, na.rm = T)/district_size) %>%
  ungroup()

dat_long <- dat_final %>%
  pivot_longer(contains('perc'),
               names_to = 'school_demos',
               names_prefix = 'perc_',
               values_to = 'percents')

#dat_final[rowSums(is.na(dat_final)) > 0,]

rm(list=setdiff(ls(), c('dat_final', 'dat_long')))
```

```{r}
comparison_schools <-
  dat_final %>%
  mutate(harsh_10 = ntile(harsh_ps, 10)) %>%
  filter(harsh_10 %in% c(1,10)) %>%
  mutate(category = if_else(harsh_10 == 1, 'Fewest', 'Most')) %>% 
  select(-district, 
         -contains('non_white'),
         -district_size, 
         -school_name, 
         -fac_schtype,
         -starts_with('d_')) %>% 
  pivot_longer(starts_with('perc_'),
               names_to = 'demographics', 
               names_prefix = 'perc_',
               values_to = 'percent') 
```

```{r}
school_plot <- 
comparison_schools %>% 
  ggplot(aes(y = 
               fct_reorder(demographics, percent), 
             x = percent)) + 
  geom_jitter(aes(color = category, 
                  shape = category), 
              width = 0,
              alpha = 0.6) + 
  lims(x = c(0,100)) +
  scale_y_discrete(breaks = c(
    'black', 
    'frl', 
    'white',
    'hisp', 
    'esol', 
    'migrant'
  ),
    labels = c(
    'Black', 
    'FRL',
    'White', 
    'Hispanic', 
    'ESOL',
    'Migrant'
  )) +
  labs(x = 'Percent of School (%)', 
       y = '', 
       color = 'Harsh Punishments per Student', 
       shape = 'Harsh Punishments per Student') +
  theme_minimal() + 
  scale_color_OkabeIto()
```

```{r}
school_animation <- 
  school_plot + 
  transition_states(states = category, transition_length = 2) + 
  labs(title = 'Demographics of Schools with the {closest_state} 
Harsh Punishments per Student') + 
  theme(plot.title = element_text(hjust=0.5, size=rel(3)), 
        #plot.caption = element_text(hjust=0.5, size=rel(3)), 
        axis.text.y = element_text(size = rel(2)), 
        axis.text.x = element_text(size = rel(2)), 
        legend.title = element_text(size = rel(2)),
        legend.text = element_text(size = rel(2)), 
        legend.position = 'bottom') + 
  enter_fade() +    
  exit_fade() 

school_gif <- animate(school_animation, 
                        nframes = 100, 
                        height = 600, 
                        width = 800, 
                        start_pause = 5, 
                        end_pause = 5)
```

```{r}
lmertree_TA <- dat_final %>% 
  mutate(`% Black` = perc_black, 
         `School Type` = fac_schtype,
         `% FRL` = perc_frl) %>% 
  lmertree(
     formula = 
       harsh_ps ~ 1 | 
       (1 | district/`School Type`) | 
       total +
       `School Type` + 
       `% Black` + 
       perc_hisp + 
       perc_migrant + 
       perc_esol + 
       `% FRL` +
       d_black + 
       d_hisp + 
       d_migrant + 
       d_esol + 
       d_frl, 
     alpha = 0.001, 
     bonferroni = T, 
     cluster = district,
     minsize = 230)

```

```{r}
asterisk_sign <- function(p_value) {
  if (p_value < 0.001) return(c("p_value < 0.001"))
  if (p_value < 0.01) return(c("p_value < 0.01"))
  if (p_value < 0.05) return(c("p_value < 0.05"))
  else return("")}

p1 <- lmertree_TA$tree[1]

tree <-
  ggparty(p1) +
  geom_edge(size = 1.2) +
  geom_edge_label() +
  geom_node_label(aes(label = splitvar), 
                  ids = "inner") +
  geom_node_plot(gglist = list(
    geom_boxplot(aes(y = harsh_ps, 
                     color = `School Type`)), 
    labs(y = 'Punishments/Student'),
    theme_minimal(),
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(), 
          axis.line.x = element_line(size = 1.5), 
          axis.line.y = element_line(size = 1.5), 
          panel.grid.minor.x = element_blank(), 
          panel.grid.major.x = element_blank()),
    lims(y = c(0, 1.5))), 
    shared_axis_labels = T) +
  geom_node_label(
    line_list = list(aes(label = paste('N = ' , nodesize)),
                     aes(label = splitvar),
                     aes(label = asterisk_sign(p.value))),
    # set graphical parameters for each line
    line_gpar = list(
      list(#size = 8,
        col = "black",
        fontface = "bold"),
      list(size = 12),
      list(size = 8)),
    ids = "inner") +
  geom_node_label(
    aes(label = paste0("N = ", nodesize)),
    fontface = "bold",
    ids = "terminal") + 
  labs(title = 'Mixed Effects Regression Tree of Harsh Punishments per Students') +
  theme(plot.title = element_text(hjust = 0.5))

  
ggsave('tree_plot.png', tree, path = here::here('Data'))
```

```{r}
summary_1 <- dat_final %>% 
  mutate(`Quintile Black Students` = ntile(perc_black, 5)) %>% 
  group_by(`Quintile Black Students`) %>% 
  summarize(`Average % Black Students` = mean(perc_black), 
           `Average HPS` = mean(harsh_ps))

comparison_1 <- summary_1$`Average HPS`[1]

percent_change_1 <- summary_1 %>% 
  mutate(`% Increase in HPS from 1st Quintile` = 
           (`Average HPS`- comparison_1)/comparison_1*100)

summary_2 <- dat_final %>% 
  mutate(`Quintile FRL Students` = ntile(perc_frl, 5)) %>% 
  group_by(`Quintile FRL Students`) %>% 
  summarize(`Average % FRL Students` = mean(perc_frl), 
           `Average HPS` = mean(harsh_ps))

comparison_2 <- summary_2$`Average HPS`[1]

percent_change_2 <- summary_2 %>% 
  mutate(`% Increase in HPS from 1st Quintile` = 
           (`Average HPS`- comparison_2)/comparison_2*100)

```

```{r}
# Geographic Data (Teachers & Admin Page)

#GA <- lea_get(state = 'GA') 
#maptools::writeSpatialShape(GA, 'GA_map')
GA_1 <- maptools::readShapeSpatial('GA_map.shp')

# GA_sf <- 
#   lea_get(state = 'GA') %>%

GA_sf <- GA_1 %>% 
  st_as_sf() %>% 
  mutate(district = 
           str_replace(string = NAME, 
                       pattern = " District", ""), 
         district = 
           str_replace(string = district, 
                       pattern = " Schools", ""), 
         district = 
           str_replace(string = district, 
                       pattern = " School", "")
         )
```

```{r}
#disc_demo %>% filter(system_name == 'Macon County')

dat_district <- 
  dat_final %>% 
  select(district, district_size, starts_with('d_')) %>% 
  unique()

GA_districts <- 
  GA_sf %>% 
  left_join(dat_district) %>% 
  mutate(harsh_qt = factor(ntile(d_harsh, 5)), 
         black_qt = factor(ntile(d_black, 5)),
         frl_qt = ntile(d_frl, 5), 
         harsh_3 = ntile(d_harsh, 3), 
         black_3 = ntile(d_black, 3), 
         frl_3 = ntile(d_frl, 3))
```

```{r}
b_map <- GA_districts %>% 
  mutate(`Quintile Harsh Punishment` = harsh_qt,
    Demographics = paste('\n', '(', district, ')',
                         '\n', round(d_black, 1), '% Black', 
                         '\n', round(d_hisp, 1), '% Hispanic', 
                         '\n', round(d_migrant, 1), '% Migrant', 
                         '\n', round(d_frl, 1), '% FRL', 
                         sep = "")
         ) %>% 
  ggplot(aes(geometry = geometry)) + 
  geom_sf(aes(fill = `Quintile Harsh Punishment`, text = Demographics)) +
  scale_fill_manual(
    values =
      c('#a9c2f4',
        '#7ca2ee',
        '#4f82e8',
        '#2262e2',
        '#184eb9'),
    na.value = '#6a6b6c') +
  theme_void()  +
  labs(fill = 'Quintile Harsh Punishments',
       title = 'Distribution Harsh Punishments per Student')


plotly_map1 <- 
  ggplotly(b_map) 

```

General 
===

Column {data-width=350, .tabset}
-----------------------------------------------------------------------

### Introduction

**Background**

As a former teacher and prevention scientist, I can say confidently that administrators do not give disciplinary action to students in a completely objective manner. To be fair, administrators are human, and all humans bring bias into their decision-making process. However, when the bias clearly follows demographic characteristics (e.g., race-ethnicity, income, etc.) and when it influences the life course of a young person, it cannot be ignored.

Bias in disciplinary action has been studied formally across US schools, with much of the results echoing the [disproportionate "exclusionary" disciplinary actions given to black students](https://epaa.asu.edu/ojs/article/viewFile/2787/1911), compared to black students' other-racial-ethnic counterparts, particularly white students. Exclusionary disciplinary action is any action which removes a student from the school (e.g., suspension, expulsion, etc.). Such exclusionary punishments are shown to [contribute directly to the school-to-prison pipeline](https://www.tandfonline.com/doi/full/10.1080/10665684.2014.958965). This is not meant to be a deep-dive into the literature, but this [Google Scholar](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C38&q=inequity+in+student+discipline&btnG=) link can get you started if you're interested.



The interactive map shows harsh punishments per student, represented as quintiles of the underlying distribution, for each district. In addition to these, district names and several district demographic characteristics are presented by hovering over a district line.

a call to change [reference](https://www.tandfonline.com/doi/pdf/10.1080/00098655.2015.1121120)

**Useful Definitions:** 

* A *quintile* is exactly 20% (or $\frac1{5^{th}}$) of the population; these are formed by arranging a variable in order and dividing the distribution into 5 equal bins. A district in the $1^{st}$ quintile for harsh punishments per student is one of the 20% of districts with the fewest harsh punishments per student.

* *Harsh punishments* are punishments that either remove students from the school or involve physically disciplining students. The disciplinary actions reported that match this definition include:

  * Out of school suspension
  * Juvenile court referral
  * Permanent expulsion
  * Physical restraint
  * Corporal punishment

  
* *Free and Reduced-Price Lunch Status* (FRL) is related to family income and is used as a crude approximation of a child coming from a low-income family. 

* *English for Speakers of Other Languages* (ESOL)
  
**Data**

The data set represents 2,141 schools in 198 districts across the state of Georgia, and merges data from the [Governer's Office of Student Achievement](https://gosa.georgia.gov/report-card-dashboards-data/downloadable-data) and the [Georgia Department of Education](https://www.gadoe.org/data-reporting/Pages/default.aspx). 


Column {data-width=650, .tabset} 
-----------------------------------------------------------------------

### Figure 1.

```{r }
plotly_map1 
```

### Code (Figure 1)

```{r, echo = T, eval = F}
b_map <- GA_districts %>% 
  mutate(`Quintile Harsh Punishment` = harsh_qt,
    Demographics = paste('\n', '(', district, ')',
                         '\n', round(d_black, 1), '% Black', 
                         '\n', round(d_hisp, 1), '% Hispanic', 
                         '\n', round(d_migrant, 1), '% Migrant', 
                         '\n', round(d_frl, 1), '% FRL', 
                         sep = "")
         ) %>% 
  ggplot(aes(geometry = geometry)) + 
  geom_sf(aes(fill = `Quintile Harsh Punishment`, text = Demographics)) +
  scale_fill_manual(
    values =
      c('#a9c2f4',
        '#7ca2ee',
        '#4f82e8',
        '#2262e2',
        '#184eb9'),
    na.value = '#6a6b6c') +
  theme_void()  +
  labs(fill = 'Quintile Harsh Punishments',
       title = 'Distribution Harsh Punishments per Student')


plotly_map1 <- 
  ggplotly(b_map)
plotly_map1
```

School Admin
===

column {data-width=400, .tabset}
-----------------------------------------------------------------------

### Profiles of Schools

**How exactly do schools who give many harsh punishments per student compare to those who give few?**

**Figure 2** compares demographic characteristics for schools with the fewest and most harsh punishments per student at the school and district level. Schools which give the most harsh punishments per student have many more free/reduced-price lunch eligible students than those who give the least. These schools also have many more black students and many fewer white students. Similar differences can be seen at the district level. This necessitates both a deeper investigation into the equity in use of these harsh punishments and exploration of possible alternative punishments that allow students to learn from mistakes in a school setting. Teachers and Administration in districts with such demographics should 

**How much does disciplinary action change across percent FRL Eligible and percent black students per school?**

**Table 1** & **Table 2** explore these differences. Comparing schools with the most FRL eligible to the least shows 400x more harsh punishments in the former than the latter; similar comparisons for percent black students show almost 350x more harsh punishments in schools with the highest percent black students compared to those with the lowest percent black students. 

```{r}
percent_change_2 %>%
  round(digits = 2) %>%
  gt() %>%
  tab_header(
    title = 'Table 1. Inequity in Harsh Punishments per Student (HPS) across % FRL Students') %>%
  tab_options(table.width = pct(95))

percent_change_1 %>%
  round(digits = 2) %>%
  gt() %>%
  tab_header(
    title = 'Table 2. Inequity in Harsh Punishments per Student (HPS) across % Black Students') %>%
  tab_options(table.width = pct(95))
```

### School-Level Info

```{r}
dat_school_level <-
  dat_final %>% 
  transmute(school_name,
            district = district,
            harsh_punishments = harsh, 
            harsh_per_student = harsh_ps,
            school_type = factor(fac_schtype, 
                                 levels = c('E', 'M', 'H', 'K12'), 
                                 labels = c('Elementary', 'Middle', 'High', 'K-12')),
            number_of_students = total, 
            percent_black = perc_black, 
            percent_hispanic = perc_hisp, 
            percent_white = perc_white, 
            percent_migrant = perc_migrant, 
            percent_ESOL = perc_esol) %>% 
  mutate_if(is.numeric, round)
  
  
reactable(dat_school_level, 
    filterable = T,
    highlight = T, 
    striped = T, 
    outlined = T,
    defaultSorted = c('harsh_per_student'),
    defaultColDef = colDef(
      header = function(x) str_to_title(gsub("_", " ", x))
    ),
    defaultSortOrder = 'desc'
  )
```


column {data-width=600, .tabset}
-----------------------------------------------------------------------

### Figure 2.

```{r}
school_gif
```

### Code (Figure 2)

```{r, echo = T, eval = F}
school_plot <- 
comparison_schools %>% 
  ggplot(aes(y = 
               fct_reorder(demographics, percent), 
             x = percent)) + 
  geom_jitter(aes(color = category, 
                  shape = category), 
              width = 0,
              alpha = 0.6) + 
  
  lims(x = c(0,100)) +
  scale_y_discrete(breaks = c(
    'black', 
    'frl', 
    'white',
    'hisp', 
    'esol', 
    'migrant'
  ),
    labels = c(
    'Black', 
    'FRL',
    'White', 
    'Hispanic', 
    'ESOL',
    'Migrant'
  )) +
  labs(x = 'Percent of School (%)', 
       y = '', 
       color = 'Harsh Punishments per Student', 
       shape = 'Harsh Punishments per Student') +
  theme_minimal() + 
  scale_color_OkabeIto()

school_animation <- 
  school_plot + 
  transition_states(states = category, transition_length = 2) + 
  labs(title = 'Demographic Characteristics of Schools with the {closest_state}
Harsh Punishments per Student') + 
  theme(plot.title = element_text(hjust=0.5, size=rel(3)),
        #plot.caption = element_text(hjust=0.5, size=rel(3)), 
        axis.text.y = element_text(size = rel(2)), 
        axis.text.x = element_text(size = rel(2)), 
        axis.title.x = element_text(size = rel(2)),
        legend.text = element_text(size = rel(2)), 
        legend.title = element_text(size = rel(2)),
        legend.position = 'bottom') + 
  enter_fade() +    
  exit_fade() 

school_gif <- animate(school_animation, 
                      nframes = 100, 
                      height = 600, 
                      width = 800, 
                      start_pause = 5, 
                      end_pause = 5)
school_gif
```

Researchers
===

Column {data-width=350, .tabset}
-----------------------------------------------------------------------

### Description 

Parameter instability tests are relatively infrequently used tools in education, probably because their long-standing inability to take into account nested data structures (like those made by schools nested in districts). Recent advancements from [Zeileis, Hothorn, and Hornik's (2008)](https://www.tandfonline.com/doi/abs/10.1198/106186008X319331) general linear model regression trees have extended them to incorporate such nesting, thanks to [Fokkema & Zeileis (2018)](https://pubmed.ncbi.nlm.nih.gov/29071652/). Such models are extremely powerful and flexible. They use recursive partitioning to find subgroup differences in any regression model, as well as determining which variables moderate the relationship specified to varying degrees. 

These models allow you to specify a mixed-effect model and provide partitioning variables. After accounting for level-2 variance, the model runs many linear models and determines which parameters differ along partitioning variables. A variant of an *F* test is then used to determine if differences among partitioning variables are significant at a pre-specified alpha, controlling for inflation with Bonferroni corrections. If these differences are significant, subsequent splits can be identified, which would suggest an interactive effect.

Single imputation was used to fill missing data. The model shown here only reports group differences at the *p* < 0.001, after Bonferroni corrections, and with the minimum acceptable node as as 10% of the total sample (i.e., 230 schools/node).

An intercept-only model was fit for Harsh Discipline per student at the school level. Conditional variances were specified such that schools were nested in their districts. The model explored for parameter instability across level-1 and level-2 with all school- and district-level covariates (e.g., percent racial/ethnic composition, percent FRL status, percent English second language, and percent migrant students). 

### Results

**Figure 3** shows results of this exploratory model

The variable which shows the greatest inequity in harsh punishments per student is school type, with middle and high schools displaying higher average harsh punishments per student than elementary and K-12 schools. Among middle and high schools, schools with higher than ~61% FRL eligible student have higher average harsh punishments per student than those with less than ~61%. 

Among elementary and middle schools, the variable which creates greatest instability in estimation of the intercept is percent black students, with schools that have more than 35% black students displaying higher average harsh punishments per student. 

An important note here is that the figure actually shows the entire distribution across elementary and middle schools, but many outliers for middle and high schools were omitted from this visualization to make comparison of the average and interquartile ranges easier. 

The model predicts *middle and high schools with less than ~61% FRL eligible students* will average **1 harsh punishment for every 9 students**. In *middle and high schools with more than ~61% FRL eligible students*, this number increases to over **1 harsh punishment for every 4 students**. In *elementary and K-12 schools with less than 35% black students*, we see only **1 harsh punishment per every 20 students**. For *elementary and K-12 schools with more than 35% black students*, we see more than **1 harsh punishment per every 10 students**.

This provides evidence that there is significant inequity in distribution of harsh punishments per student across schools, family income (i.e., FRL status), and percent black students. Next steps should explore interventions which can improve administrative decision-making to minimize such inequity. 


Column {data-width=650, .tabset}
-----------------------------------------------------------------------

### Figure 3. 

```{r}
# tree_pic <- png::readPNG(here::here('Data', 'tree_plot.png')) 
# grid::grid.raster(tree_pic)
tree
```


### Code (Figure 3)

```{r, echo = T, eval = F}
asterisk_sign <- function(p_value) {
  if (p_value < 0.001) return(c("p_value < 0.001"))
  if (p_value < 0.01) return(c("p_value < 0.01"))
  if (p_value < 0.05) return(c("p_value < 0.05"))
  else return("")}

p1 <- lmertree_TA$tree[1]

tree <-
  ggparty(p1) +
  geom_edge(size = 1.2) +
  geom_edge_label() +
  geom_node_label(aes(label = splitvar), 
                  ids = "inner") +
  geom_node_plot(gglist = list(
    geom_boxplot(aes(y = harsh_ps, 
                     color = `School Type`)), 
    labs(y = 'Punishments/Student'),
    theme_minimal(),
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(), 
          axis.line.x = element_line(size = 1.5), 
          axis.line.y = element_line(size = 1.5), 
          panel.grid.minor.x = element_blank(), 
          panel.grid.major.x = element_blank()),
    lims(y = c(0, 1.5))), 
    shared_axis_labels = T) +
  geom_node_label(
    line_list = list(aes(label = paste('N = ' , nodesize)),
                     aes(label = splitvar),
                     aes(label = asterisk_sign(p.value))),
    # set graphical parameters for each line
    line_gpar = list(
      list(#size = 8,
        col = "black",
        fontface = "bold"),
      list(size = 12),
      list(size = 8)),
    ids = "inner") +
  geom_node_label(
    aes(label = paste0("N = ", nodesize)),
    fontface = "bold",
    ids = "terminal") + 
  labs(title = 'Mixed Effects Regression Tree of Harsh Punishments per Students') +
  theme(plot.title = element_text(hjust = 0.5))

tree
# ggsave('tree_plot.png', tree, path = here::here('Data'))
# tree_pic <- png::readPNG(here::here('Data', 'tree_plot.png')) 
# grid::grid.raster(tree_pic)
```
